version: '3'
services:
  vue-app:
    container_name: vue-app
    build: .
    ports:
      - "8080:8080" # Порт, на котором будет доступно приложение Vue.js
    volumes:
      - .:/app # Монтируем текущий каталог внутрь контейнера